### ISSUE TITLE
showtext renders tiny text on higher resolution png device 

### ISSUE THREAD

**Issue by ellisp** [yixuan/showtext#10]
Thanks for the great package.

Problem is as per this example:

```R
library(showtext)
library(ggplot2)

p <- ggplot(mtcars, aes(x = disp, y = mpg, label = gear)) + 
  geom_smooth() +
  geom_text()

png("noshowtext.png", width = 6000, height = 4000, res = 600)
  print(p)
dev.off()

png("showtext.png", width = 6000, height = 4000, res = 600)
  showtext.begin()
  print(p)
  showtext.end()
dev.off()
```

Here's the version without showtext:
![noshowtext](https://cloud.githubusercontent.com/assets/5740570/20652211/ca58da92-b559-11e6-81c4-d9cbaaf90c83.png)

And here's the version that has it:
![showtext](https://cloud.githubusercontent.com/assets/5740570/20652212/cff1f7e0-b559-11e6-8299-365b4522b856.png)

The text is all there, just very very small. It looks like the other objects (lines etc) are ok, but the text doesn't know how to deal with the higher resolution png device.

This has been driving me batty until I worked out that showtext is the problem.  On my home setup I can get around this (now that I know what it is) by creating SVGs and using ImageMagick to convert them to PNG when I need a PNG, but I can't do that at my locked down work network.  If there's a fix it would be awesome!

**Comment by yixuan** [comment]
Hi Peter,
Take a look at the `showtext.opts()` function that has a `dpi` parameter:

```r
showtext.auto()
op = showtext.opts(dpi = 600)

png("showtext_fix.png", width = 6000, height = 4000, res = 600)
  print(p)
dev.off()

## restore previous options
showtext.opts(op)
```
![showtext_fix](https://cloud.githubusercontent.com/assets/216398/20653096/13577c2e-b4d5-11e6-8909-aaf3f36d1909.png)

**Comment by ellisp** [comment]
ok great that seems to fix this problem.  In our actual application we have a problem after that fix that legends don't show up now in pngs made this way (again, PDF and SVG are ok), but at least the text that is there is visible.  And in simpler examples I can't reproduce that legend problem; so I think that means this tiny text issue is fixed, thanks very much (but I might be back if we can get a reproducibly disappearing legend!).
