### ISSUE TITLE
showtext and knitr

### ISSUE THREAD

**Issue by larmarange** [yixuan/showtext#11]
It seems that `showtext` doesn't work with `knitr`.

**Comment by yixuan** [comment]
Hi Joseph, did you use the `fig.showtext` option in `knitr`?
You may want to take a look at this [article](http://statr.me/2014/07/showtext-with-knitr/), and also the R Journal [paper](https://journal.r-project.org/archive/2015-1/qiu.pdf).

**Comment by larmarange** [comment]
Sorry. It was a local bug.

**Comment by stla** [comment]
Hello,
Does it also work with knitr Sweave, with pdf plots ?
