### ISSUE TITLE
New R (3.4) introduces errors when using showtext

### ISSUE THREAD

**Issue by thomasjwood** [yixuan/showtext#12]
In the previous R version (3.3.3), this

```
library(ggplot2)
library(showtext)

font.add.google("Lato")

p1 <- ggplot(diamonds, aes(depth, price)) +
  geom_point() +
  theme_minimal(base_family = "Lato")

showtext.auto()
ggsave(plot = p1, "trial.pdf")

```
works:

![image](https://cloud.githubusercontent.com/assets/1422023/25392703/5e281604-29a7-11e7-81ad-25302562d1e5.png)

but in the version of R (3.4) you instead get

```
Error in grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y,  : 
  invalid font type
```

**Comment by yixuan** [comment]
Did you try to reinstall the package using R 3.4?

**Comment by thomasjwood** [comment]
That fixed it--thanks! Sorry for the false alarm.

**Comment by yixuan** [comment]
No problem. Thanks for the report.
