### ISSUE TITLE
sysfonts not loading/Image not found

### ISSUE THREAD

**Issue by drewmag** [yixuan/showtext#13]
After upgrading to a newer Mac, I have this error show up whenever I try to load `showtext`:

`Error: package or namespace load failed for ‘sysfonts’:
 .onLoad failed in loadNamespace() for 'sysfonts', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/sysfonts/libs/sysfonts.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/sysfonts/libs/sysfonts.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/sysfonts/libs/sysfonts.so
  Reason: image not found`

How can I fix this?

**Comment by yixuan** [comment]
It looks like a linking problem. Some of the required system libraries are not found by the package. How did you install these packages? Have you tried to reinstall `sysfonts` and `showtext`?

**Comment by arielswan** [comment]
I have this problem too, also can't load `showtext` , and when I reinstalled the package `sysfonts` , it shows:

> install.packages("sysfonts")
试开URL’https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/sysfonts_0.7.1.tgz'
Content type 'application/x-gzip' length 1130201 bytes (1.1 MB)
==================================================
downloaded 1.1 MB
The downloaded binary packages are in
	/var/folders/cp/927714q12mlcjz2brcssbydc0000gp/T//RtmpwLLxFL/downloaded_packages
> library(sysfonts)
错误: package or namespace load failed for ‘sysfonts’:
 loadNamespace()里算'sysfonts'时.onLoad失败了，详细内容：
调用: dyn.load(file, DLLpath = DLLpath, ...)
错误: 无法载入共享目标对象‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/sysfonts/libs/sysfonts.so’：:
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/sysfonts/libs/sysfonts.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/sysfonts/libs/sysfonts.so
  Reason: image not found

What should I do?

**Comment by yixuan** [comment]
@arielswan Have you tried to remove all relevant packages and reinstall?

**Comment by arielswan** [comment]
@yixuan  it seems `sysfonts` has a problem, so i just reinstall this package

`> library(showtext)
载入需要的程辑包：sysfonts
Error: package or namespace load failed for ‘sysfonts’:
 loadNamespace()里算'sysfonts'时.onLoad失败了，详细内容：
  调用: dyn.load(file, DLLpath = DLLpath, ...)
  错误: 无法载入共享目标对象‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/sysfonts/libs/sysfonts.so’：:
  dlopen(/Library/Frameworks/R.framework/Versions/3.4/Resources/library/sysfonts/libs/sysfonts.so, 6): Library not loaded: /opt/X11/lib/libfreetype.6.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.4/Resources/library/sysfonts/libs/sysfonts.so
  Reason: image not found
错误: 无法载入程辑包‘sysfonts’`

Should I reinstall any other packages? and what else packages can I reinstall?

**Comment by yixuan** [comment]
Hi @arielswan , unfortunately I don't have a Mac to test on. Something you can try is to reinstall R, and rebuild packages that were built for earlier version.
```r
update.packages(checkBuilt = TRUE)
```
A similar problem was resolved by this method: https://d.cosx.org/d/419266-showtext-sysfonts.

**Comment by tcarnus** [comment]
FYI installing https://www.xquartz.org/ worked for me

**Comment by arielswan** [comment]
OMG!!!!!!!!  It worked after I installed "XQuartz", Thankyou sooooooooo much~ @tcarnus @yixuan

**Comment by yixuan** [comment]
Cool. Thanks for the help @tcarnus !

**Comment by DaveParr** [comment]
This looks specifically as if there is a change between Sierra and High Sierra. XQuartz worked for me too.

**Comment by yixuan** [comment]
Installing XQuartz seems to solve most of the problems. Let me close this issue at this moment.

**Comment by mayrop** [comment]
Amazing @tcarnus, it worked !
