### ISSUE TITLE
Error adding fonts using font.add.google()

### ISSUE THREAD

**Issue by noelnamai** [yixuan/showtext#14]
```
> library("showtext")
>
> font.add.google("Avenir Next", "avenir")
Error in search_db(name) : font not found
> 
```

**Comment by yixuan** [comment]
It seems that this font was recently added by Google, and I need to update the font database. I'll fix this late today.

**Comment by yixuan** [comment]
OK, it turns out that this font is not open source and thus cannot be loaded from Google Fonts. See the information [here](https://fonts.google.com/?query=Avenir+Next).

**Comment by noelnamai** [comment]
@road2stat

**Comment by Jrakru** [comment]
I have the same issue but the font is supposed to have an open font license.
```
> library(showtext)
> font_add_google("Staatliches","Staatliches")
Error in search_db(name, db_cache, handle) : font not found
```

**Comment by yixuan** [comment]
@Jrakru Can you try `font_add_google("Staatliches", "Staatliches", db_cache = FALSE)`?

**Comment by Cami1992** [comment]
>font_add(family = "Gill Sans Nova Book", regular = "C:/Users/Linus/Documents/District_Profiles/Gill Sans Nova Book.ttf")
font_families()
 Error in check_font_path(regular, "regular") : 
font file not found for 'regular' type
>font_add_google("Gill Sans Nova", "gill", db_cache = FALSE)
 Error in search_db(name, db_cache = TRUE, handle = handle) : 
font not found

**Comment by yixuan** [comment]
Hi @Cami1992, please consider to open a new issue as this was marked closed. For your second question, it is because "Gill Sans Nova" is not in the Google Fonts collection. I cannot debug your first question since I do not have the "Gill Sans Nova Book.ttf" file. You can try to upload the file so I can take a look.
