### ISSUE TITLE
Showtext prevents creating cairo-png objects when labels are blank

### ISSUE THREAD

**Issue by pritz2** [yixuan/showtext#20]
Created a plot, wanted to create a custom x-axis, so I set xlab to " " and xaxt="n". Found that the text and axis commands no longer drew to my graph!

```R
library("showtext")
showtext.opts(dpi = 144)
showtext.auto()

#Open cairo-png device
png(filename = "output.png", type = "cairo-png")

# plot basic x/y graph
x<-1:10
y<-1:10
plot(x, y, ylab="Y axis",xlab=" ",xaxt = "n")

# add text and axis
text(x, y, label=y, pos=3)
axis(1, at=x, labels=x)

# close the device
dev.off()
```

![Graph without labels](https://user-images.githubusercontent.com/7356022/42352655-b1bc5746-8070-11e8-908b-dad162c91a68.png)

So I changed the plot line of code to be null instead of a space:

```R
plot(x, y, ylab="Y axis",xlab="",xaxt = "n")
```

And then the axes and text appeared

![Graph with labels](https://user-images.githubusercontent.com/7356022/42352673-c9107c6a-8070-11e8-965c-c2f893d73643.png)

Am I missing something fundamental or is this a bug?

**Comment by yixuan** [comment]
This seems to be a genuine bug. I'll try to figure it out.

**Comment by yixuan** [comment]
https://github.com/yixuan/showtext/commit/820bfb39b0fe16a1aa4ef55f99da6ec4fb979b2d fixes this issue. I'll prepare a CRAN release soon.

**Comment by yixuan** [comment]
On CRAN now.
