### ISSUE TITLE
Google fonts don't show on my chart, only my system default

### ISSUE THREAD

**Issue by chrismp** [yixuan/showtext#24]
I am using RStudio Debian 9.3 I ran this code:

```
library(showtext)
font_add_google("Lobster", "lobster")

showtext_auto()

plot(1, pch = 16, cex = 3)
text(1, 1.1, "A fancy dot", family = "lobster", col = "steelblue", cex = 3)
```

And I saw this in the "Plots" section of RStudio.
![rplot01](https://user-images.githubusercontent.com/7936571/45601802-ec1df800-b9e0-11e8-9e9a-36825c05b0fc.png)

Any idea why the font displays wrong?

**Comment by yixuan** [comment]
Hi, this is a known limitation: https://github.com/yixuan/showtext/issues/7. I am afraid currently there is no good way to get rid of it, so I suggest explicitly opening a default graphics window.
