### ISSUE TITLE
showtext appears to be double spacing labels/titles

### ISSUE THREAD

**Issue by PDjupe** [yixuan/showtext#26]
Love the ease of this package. But when I use the "\n" function to separate labels to a second line I am getting double spacing which I can't correct outside of photoshop. Here's an example with labels and titles showing the double spacing. 

fpol %>% filter(pid7!="NA") %>% ggplot(., aes(x=q18_1, y=factor(pid7), fill=..x..)) +
  geom_density_ridges_gradient(rel_min_height=.02) +
  scale_fill_gradient2(low="dodgerblue3", high="firebrick3", mid="white", midpoint=50) +
  theme_minimal() +
  labs(x="", y="", title="Only Strong Republicans Are Happy\nwith Trump Admin's Management", caption="Source: February 2018") + 
  theme(legend.position = "none") +
  scale_x_continuous(breaks=c(0,25,50,75,100), labels=c("Extremely\nUnhappy","25","Neither\nHappy\nNor\nUnhappy", "75", "Extremely\nHappy")) +
    theme(text=element_text(family="JSans", size=20)) 

![happy_w_trump](https://user-images.githubusercontent.com/40002515/47366828-7591ab80-d6ac-11e8-8e1e-71a5ec55e234.png)

**Comment by larmarange** [comment]
Same issue observed

**Comment by yixuan** [comment]
I'll take a look some time later this week.

**Comment by yixuan** [comment]
I was trying to investigate this issue today, but I couldn't reproduce it. The spacing seems correct for the minimal example below. Can someone give me a (runnable) example that has double spacing?

```r
library(showtext)
library(ggplot2)

showtext_auto()

dat = data.frame(x = c("AAA\nAAA", "BBB\nBBB", "CCC\nCCC"), y = 1:3)
x11()
ggplot(dat, aes(x = x, y = y)) +
    geom_bar(stat = "identity") +
    ggtitle("First Line\nsecond line") +
    theme_grey(base_family = "sans")
```

![image](https://user-images.githubusercontent.com/216398/50015519-cdee7680-ff94-11e8-8b9b-fc31ac2e0ab2.png)

**Comment by PDjupe** [comment]
Hi-
Thanks for taking a look. It shows up correctly (no extra spacing) in the
preview window, but once I ggsave it, the spacing appears. I added a
googlefont to your code.

library(showtext)
library(ggplot2)
font_add_google("Merriweather", "Merri", regular.wt = 400)
showtext_auto()

dat = data.frame(x = c("AAA\nAAA", "BBB\nBBB", "CCC\nCCC"), y = 1:3)
x11()
ggplot(dat, aes(x = x, y = y)) +
  geom_bar(stat = "identity") +
  ggtitle("First Line\nsecond line") +
  theme_grey(base_family = "Merri")
ggsave(file="shotwtext_example.png", type="cairo-png", width=5, height=5)

**Comment by larmarange** [comment]
The issue is also observed when using showtext within a Rmarkdown document.

**Comment by yixuan** [comment]
OK, now I know the problem. The fact is not that the spacing is doubled, but that the font sizes are made smaller. `ggsave()` has a default `dpi = 300` argument, while `showtext_opts()` has `dpi = 96`. Simply add the following line will fix the issue.
```r
showtext_opts(dpi = 300)
``` 

The same reason applies to Rmarkdown. You need to make sure the `dpi` knitr option is consistent with the one in `showtext`.

**Comment by larmarange** [comment]
Would it be possible to find a way in Rmarkdown for `showtext` to detect automatically the dpi used by `knitr`?

**Comment by yixuan** [comment]
@larmarange I find that adding the following option to the document header automatically solves the problem. Can you confirm this?

```yaml
---
output:
    html_document:
        fig_retina: 1
---
```
