### ISSUE TITLE
showtext.opts()' is now renamed to 'showtext_opts() . Error in Power BI Pro

### ISSUE THREAD

**Issue by somaghosh1** [yixuan/showtext#27]
I’m publishing a  Power BI report with R script in Power BI Pro and getting following error. I’m not using anywhere 'showtext.opts(), 'font.add() function. How can I resolve this error.

Script Runtime Error

'showtext.opts()' is now renamed to 'showtext_opts()'
The old version still works, but consider using the new function in future code
'showtext.begin()' is now renamed to 'showtext_begin()'

**Comment by yixuan** [comment]
According to the [documentation](https://docs.microsoft.com/en-us/power-bi/visuals/service-r-visuals) I guess the Power BI service is using `showtext` in the backend. However, I do not have access to the code at that side, so I suggest you asking the question in the Power BI community, similar to this one: <https://community.powerbi.com/t5/Report-Server/R-visual-responsive-visualization-in-power-BI/td-p/450875>.

**Comment by somaghosh1** [comment]
Thanks

Regards,
Soma
________________________________

**Comment by somaghosh1** [comment]
Thank you very much

Regards,
Soma





Sensitivity: Internal & Restricted
