### ISSUE TITLE
about the fond install error 

### ISSUE THREAD

**Issue by sjtuyf** [yixuan/showtext#28]
Hi,
    I want to change the font in the R, the showtext package you developed behaved well, but I can not run regularly when add the font. The error can be seen below.
    I have try mac OS and windows, but both of them failed. 
    So my questions is how to run regularly in mac or windows, can you show the one-to-one step.
    Thanks a lot.

![image](https://user-images.githubusercontent.com/35675883/67667503-f0209580-f9a8-11e9-95c5-bae45c436fdb.png)

![image](https://user-images.githubusercontent.com/35675883/67668303-a33dbe80-f9aa-11e9-84ff-c814c176b8a8.png)

**Comment by yixuan** [comment]
Did you call `showtext_auto()`? It would be more informative if you show the full code. Thanks.

**Comment by yixuan** [comment]
Let me close this issue first unless further information is provided.
