### ISSUE TITLE
Problem installing showtext.-

### ISSUE THREAD

**Issue by vate01** [yixuan/showtext#3]
Hello.

I had a problem installing the package. I get the following message:

```
gcc -I/usr/include/R/    -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz  -I/usr/include/libpng16   -D_FORTIFY_SOURCE=2    -fpic  -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4  -c util.c -o util.o
util.c: En la función ‘GetPkgEnv’:
util.c:9:23: error: expected expression before ‘==’ token
     if(TYPEOF(pkgEnv) == PROMSXP) {
                       ^
util.c: En la función ‘GetVarFromPkgEnv’:
util.c:25:23: error: expected expression before ‘==’ token
     if(TYPEOF(pkgEnv) == PROMSXP) {
                       ^
/usr/lib64/R/etc/Makeconf:134: fallo en las instrucciones para el objetivo 'util.o'
make: *** [util.o] Error 1
ERROR: compilation failed for package ‘showtext’
* removing ‘/home/vate01/R/x86_64-unknown-linux-gnu-library/3.2/showtext’
Warning in install.packages :
  installation of package ‘/home/vate01/Descargas/showtext_0.4-2.tar.gz’ had non-zero exit status
```

Could you please give me an advice to resolve this issue?

Thanks.

**Comment by yixuan** [comment]
Thanks for your report.

This sounds interesting and I've never met this type of problem before. I guess for some reason the macro `TYPEOF` was not correctly expanded by the compiler.

Could you try to download the source package, manually do the following edittings, and install again?
- Remove Line 9 to Line 13, and Line 25 to Line 29 of util.c. They are two if-statement blocks.

If this fails again, you may also post the error messages here which may help me to diagnose the problem. Also, telling you OS and R version may help as well.

**Comment by vate01** [comment]
Thanks a lot for your quickly answer!

It was a successful instalation:

```
installing to /home/vate01/R/x86_64-unknown-linux-gnu-library/3.2/showtext/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (showtext)
> library(showtext)
Loading required package: sysfonts
```

Now, I'm going to test it!

In addition, I'm on (arch)linux, with kernel 4.1.2-2.

Thanks.

**Comment by yixuan** [comment]
Glad to hear that!

However I would say that this is just a workaround which should work well in most cases but does not solve the problem fundamentally.

Is the R you are using provided by Arch or compiled by yourself?

**Comment by vate01** [comment]
`Is the R you are using provided by Arch or compiled by yourself?`

It is provided by archlinux: https://www.archlinux.org/packages/extra/i686/r/

Thanks!

**Comment by yixuan** [comment]
Could you help me do one more testing?

Using the original source package, edit line 9 and line 25 of util.c, change the word `TYPEOF` in these two lines into `(TYPEOF)` (add a pair of parentheses around `TYPEOF`), and try to install the package.

Many Thanks!

**Comment by vate01** [comment]
`Could you help me do one more testing?`

Sure. I've done and it worked!

```
remove.packages("showtext", lib="~/R/x86_64-unknown-linux-gnu-library/3.2")
install.packages("~/Descargas/showtext.tar.gz", repos = NULL, type = "source")
...
installing to /home/vate01/R/x86_64-unknown-linux-gnu-library/3.2/showtext/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (showtext)
```

Thanks!

**Comment by yixuan** [comment]
Great! So the previous problem seems to be the behavior of compiler which requires a strict syntax on the code. I'll merge these two tiny changes to the next release.

Thank you!

**Comment by yixuan** [comment]
The problem turns out to be a conflict between the different definitions of the `TYPEOF` macro in R and FreeType 2.6. This has been fixed in the newest version of `showtext`on CRAN.
