### ISSUE TITLE
RStudio 1.4 support?

### ISSUE THREAD

**Issue by cpsievert** [yixuan/showtext#31]
Just FYI, [RStudio 1.4 comes with the capability of customizing the graphics backend](https://github.com/rstudio/rstudio/blob/master/NEWS.md). Perhaps showtext could leverage that new ability to render fonts in the RStudio graphics device?

**Comment by yixuan** [comment]
Thanks for sharing the news. This looks like an interesting update. I'll try the new RStudio when it is released.

**Comment by cpsievert** [comment]
Sounds good, thanks for considering. In case you didn't know, RStudio 1. 4 is currently available in the daily builds https://dailies.rstudio.com/

**Comment by yixuan** [comment]
Good to know that. I'll have a try when I get some time for this.

**Comment by yixuan** [comment]
Tracing back to https://github.com/rstudio/rstudio/issues/2142, I accidentally found a workaround for the issue with RStudio 1.3 or earlier. Basically you just need to run the following code at the beginning of each R session:

```r
trace(grDevices::png, exit = quote({
    showtext::showtext_begin()
}), print = FALSE)
``` 

And then run any `showtext` code in RStudio:

```r
library(showtext)
font_add_google("Lobster", "lobster")
showtext_auto()

plot(1, pch = 16, cex = 3)
text(1, 1.1, "A fancy dot", family = "lobster", col = "steelblue", cex = 3)
```

Can you test if it works for you?

**Comment by cpsievert** [comment]
Nice, can confirm this works on RStudio Preview (1.3.952). I did notice, though, that exporting to pdf via the export dropdown doesn't appear to work

**Comment by yixuan** [comment]
Then you just need to add another tracer:
```r
trace(grDevices::pdf, exit = quote({
    showtext::showtext_begin()
}), print = FALSE)
```

**Comment by cpsievert** [comment]
Interestingly it appears that if the RStudioGD is already open, this `trace()` workaround doesn't work, for example, if you first plot

```r
plot(1)
```

then `trace()`

```r
trace(grDevices::png, exit = quote({
    showtext::showtext_begin()
}), print = FALSE)
```

This no longer works

```r
library(showtext)
font_add_google("Lobster", "lobster")
showtext_auto()

plot(1, pch = 16, cex = 3)
text(1, 1.1, "A fancy dot", family = "lobster", col = "steelblue", cex = 3)
```

**Comment by yixuan** [comment]
The thing is, RStudio will open a new PNG device after it plots, so the device might be already open before `trace()` is called. You can first create a fake plot to force RStudio open a new device:

```r
plot(1)
trace(grDevices::png, exit = quote({
    showtext::showtext_begin()
}), print = FALSE)
# Force the new device to apply tracer
plot.new()

library(showtext)
font_add_google("Lobster", "lobster")
showtext_auto()

plot(1, pch = 16, cex = 3)
text(1, 1.1, "A fancy dot", family = "lobster", col = "steelblue", cex = 3)
```

**Comment by cpsievert** [comment]
Oh, I see, so RStudio must close and open a new device on every `plot.new` or `grid.newpage`? Is that your understanding of it?

**Comment by yixuan** [comment]
This is my guess, but may be wrong. RStudioGD seems to have some sophisticated operations at the backend. :thinking:

Something that may be useful for checking is to set `print = TRUE` in `trace()`:
```
trace(grDevices::png, exit = quote({
    cat("device opened\n")
}), print = TRUE)

plot(1)
plot(1)
```

In one of my sessions, the result is
```
> plot(1)
Tracing grDevices:::png("/tmp/RtmpmX3pAy/b64514f1d9c54eacb9e9152db63e5b4c.png",  .... on exit 
device opened
Tracing grDevices:::png("/tmp/RtmpmX3pAy/b64514f1d9c54eacb9e9152db63e5b4c.png",  .... on exit 
device opened
> plot(1)
Tracing grDevices:::png("/tmp/RtmpmX3pAy/72a6cf6868774d568d7abc6dececba9d.png",  .... on exit 
device opened
```
I check the last PNG file and it is 0 byte, so it should be used for future plots.

**Comment by yixuan** [comment]
As the new version is already on CRAN, I guess we can close this issue first.
