### ISSUE TITLE
Enabling showtext in RStudio 1.4 leads to text clipping

### ISSUE THREAD

**Issue by cpsievert** [yixuan/showtext#32]
In RStudio 1.4, I see:

```r
library(ggplot2)
showtext::showtext_auto()
ggplot(mtcars, aes(wt, mpg)) +
  geom_point(aes(color = factor(cyl))) +
  scale_color_discrete(name = "Some very loooong name")
```

<img width="978" alt="Screen Shot 2020-04-17 at 1 43 22 PM" src="https://user-images.githubusercontent.com/1365941/79603167-6f1d9d80-80b1-11ea-9da1-c3405e832f84.png">

Without showtext, it renders as expected

<img width="980" alt="Screen Shot 2020-04-17 at 1 43 02 PM" src="https://user-images.githubusercontent.com/1365941/79603196-7b095f80-80b1-11ea-9b4c-2eadde753cb6.png">

**Comment by cpsievert** [comment]
For posterity, it looks as though the workaround in #31 doesn't help in this scenario

**Comment by yixuan** [comment]
I tested with 1.4 on Windows, and it in fact worked for me. What did it look like in your case?

**Comment by cpsievert** [comment]
It looks like first figure above (i.e., the legend title goes off the page).

I just tested on 1.4.299 and I see this with Cairo, Cairo PNG, and AGG backends (interestingly, it works ok with a Quartz backend)

**Comment by yixuan** [comment]
Not sure if you have done this, but when you use the `ragg` backend you need to trace `ragg::agg_png()`:

```r
trace(ragg::agg_png, exit = quote({
    showtext::showtext_begin()
}), print = FALSE)
```

**Comment by cpsievert** [comment]
Doing that fixes the title going off the page, but now the text is smaller than it should be (I get similar results with the cairo devices)

```r
library(ggplot2)
showtext::showtext_auto()
trace(ragg::agg_png, exit = quote({
  showtext::showtext_begin()
}), print = FALSE)
ggplot(mtcars, aes(wt, mpg)) +
  geom_point(aes(color = factor(cyl))) +
  scale_color_discrete(name = "Some very loooong name")
```

<img width="709" alt="Screen Shot 2020-05-05 at 5 54 17 PM" src="https://user-images.githubusercontent.com/1365941/81123757-75a57500-8ef9-11ea-886b-bf2036a4c12c.png">

**Comment by yixuan** [comment]
I see. I guess we tested on different versions of packages. Previously I tried to fix these issues before submitting a new version of `showtext`, but since RStudio 1.4 and `ragg` are still under active development and many things may change, I'd better update first and fix the problems when RStudio 1.4 and `ragg` get stable.

**Comment by yixuan** [comment]
Hi @cpsievert, does the new version also solve this issue?

**Comment by cpsievert** [comment]
Looks as though it's fixed! 🎉
