### ISSUE TITLE
Incorrect lineheight on high-resolution non-quartz devices

### ISSUE THREAD

**Issue by cpsievert** [yixuan/showtext#33]
In the example below, note that without showtext enabled, all three plots below produce plots with consistent lineheight, but with showtext, the last two produce a much smaller lineheight

```r
library(showtext)
library(ggplot2)

showtext::showtext_auto()

# lineheight appears ok
tmp <- tempfile(fileext = ".png")
png(tmp, type = "quartz", res = 220, width = 600, height = 400, units = "px")
print(qplot(1:10))
dev.off()
file.show(tmp)

# lineheight is much smaller (with showtext enabled)
tmp <- tempfile(fileext = ".png")
png(tmp, type = "cairo", res = 220, width = 600, height = 400, units = "px")
print(qplot(1:10))
dev.off()
file.show(tmp)

# lineheight is much smaller (with showtext enabled)
tmp <- tempfile(fileext = ".png")
Cairo::CairoPNG(tmp, res = 220, width = 600, height = 400, units = "px")
print(qplot(1:10))
dev.off()
file.show(tmp)

```

**Comment by yixuan** [comment]
The second is easy to fix. You just need to call `showtext::showtext_opts(dpi = 220)` before plotting.

The `CairoPNG` device is a bit complicated, and I'm thinking of ways to fix it.

**Comment by cpsievert** [comment]
Great, thank you. Should knitr be setting `showtext_opts(dpi = opts_current$get("dpi"))` (when `fig.showtext` is `TRUE`)?

(cc @yihui)

**Comment by cpsievert** [comment]
Thanks again for your response @yixuan! Just curious, what are the prospects of a fix for `CairoPNG` (i.e., do you think it'll ever happen)?  Totally ok to be honest if it's unlikely, just want to know what to expect.

**Comment by yixuan** [comment]
@cpsievert This is a bit more complicated than I thought. What `showtext` needs to know is whether a specific graphics device is bitmap-based (e.g. PNG) or vector-based (PDF), and the current implementation of `showtext` uses a guess based on the device name. But for Cairo devices, they share the same device name "Cairo", so `showtext` does not know whether it is a PNG or PDF or something else.

One possible solution is to ask the user to provide such information. This makes dealing with fonts easier, but is just "less automatic". Or I need to read the C code of the `Cairo` package to see if there is anything hidden in the internals that can help me distinguish different types.

**Comment by cpsievert** [comment]
Oh, good to know. And yea, maybe it's worth contributing to **Cairo** itself to add a filepath attribute to `.Device` (then you could try to infer based on the file extension), which is what **grDevices** does, for example:

```r
> png("foo.png")
> .Device
[1] "quartz_off_screen"
attr(,"filepath")
[1] "foo.png"
```

I think we could just add that information [here](https://github.com/cran/Cairo/blob/5d1d8a14e77fd7bd17a2fe9b9691a7965153b9cc/src/cairogd.c#L272) (I'm not very familiar with C, so I don't immediately see how that'd be done, but perhaps you'd know how to?)

**Comment by yixuan** [comment]
I think I have fixed this issue in the `master` branch. Can you give it a try?

**Comment by cpsievert** [comment]
Yes, `CairoPNG` looks much better now with `showtext_opts(dip = 220)`, thank you!

I also noticed in https://github.com/yixuan/showtext/commit/39bcd28f082d35939f4d1d23c25517234a71daf3 that you've added ragg awareness, but I'm noticing some degradation in the font rendering. It seems like it'd be better to do nothing for ragg as it has its own API for rendering custom fonts (via `systemfonts::register_font()`).

```r

library(showtext)
library(ggplot2)
showtext::showtext_auto()
showtext::showtext_opts(dpi = 220)
tmp <- tempfile(fileext = ".png")
ragg::agg_png(tmp, res = 220, width = 600, height = 400, units = "px")
print(qplot(1:10))
dev.off()
file.show(tmp)
```

<img width="828" alt="Screen Shot 2020-05-02 at 5 20 12 PM" src="https://user-images.githubusercontent.com/1365941/80893586-4ee90380-8c99-11ea-9bff-bd914d0da36d.png">

**Comment by yixuan** [comment]
I think this is a bug of `ragg`. You can find that if you change the bit size to be 16 in `agg_png`, the output image is correct.

```r
library(showtext)
library(ggplot2)
showtext::showtext_auto()
showtext::showtext_opts(dpi = 220)
tmp <- tempfile(fileext = ".png")
ragg::agg_png(tmp, res = 220, width = 600, height = 400, units = "px", bitsize = 16)
print(qplot(1:10))
dev.off()
file.show(tmp)
```

![a](https://user-images.githubusercontent.com/216398/80896260-9df36080-8cba-11ea-8e1e-368d5a77eb69.png)

I'll create an example and report there.

**Comment by cpsievert** [comment]
Thanks again for the `CairoPNG` fix (and for submitting that fix to **ragg**)! 🍻 

Looks as though this is working in all the cases I care about now, so I'm happy to close. 

Just curious, do you have a timeline for a new showtext CRAN release?

**Comment by yihui** [comment]
@cpsievert I just made the change in **knitr** to pass the `dpi` option to `showtext_opts()`. Thanks!
