### ISSUE TITLE
does {showtext} not work with some google fonts? eg Poppins.

### ISSUE THREAD

**Issue by ellisp** [yixuan/showtext#4]
sorry if this is just user error, but why doesn't font.add.google work with Google font Poppins? (https://www.google.com/fonts/specimen/Poppins )

``` R
> library(showtext)
> 
> # examples from https://github.com/yixuan/showtext.  They work:
> font.add.google("Gochi Hand", "gochi")
> font.add.google("Schoolbell", "bell")
> font.add.google("Covered By Your Grace", "grace")
> font.add.google("Rock Salt", "rock")
> 
> 
> # another font.  why doesn't this work?
> font.add.google("Poppins", "Poppins")
Error in .search.db(name) : font not found


```

**Comment by yixuan** [comment]
Hi @ellisp ,
It didn't work because this font was newly added by Google and I hadn't synchronized the database.
Now I believe it is all right. Could you have a try to test? Just rerun the command and you don't need to re-instlall the package.

**Comment by ellisp** [comment]
Thanks, working fine now
