### ISSUE TITLE
Text layer removed in PDF

### ISSUE THREAD

**Issue by yvanrichard** [yixuan/showtext#46]
Hi,

Showtext seems to remove the text layer when saving a figure as pdf.
But I need the text contained in the figures to be searchable across a report containing several pdf figures, just like any other text.

It works without using `showtext_auto()`, though, but I need to use specific fonts provided as ttf files.

How can I prevent the text layer from being removed?
Cheers

**Comment by yixuan** [comment]
Hi @yvanrichard,
Unfortunately right now it is not possible to do this with showtext. showtext converts characters into polygons, thus losing the text information. If you need the text to be searchable, you need to embed fonts into the PDF, and one way to do this is using the [extrafont](https://github.com/wch/extrafont) package. You also need some external software such as Ghostscript.
