### ISSUE TITLE
Error loading of showtext

### ISSUE THREAD

**Issue by kietoljw** [yixuan/showtext#48]
Hey,I am sorry to trouble you. An error appeared when I loaded it so that I did not know how to solve it.
I supposed that  I need to install the freetype. Hope that you can help me,thank you very much!
<img width="450" alt="Snipaste_2021-03-29_23-27-04" src="https://user-images.githubusercontent.com/81357761/112860957-edb6f380-90e6-11eb-8f34-4e55cc998dca.png">

**Comment by yixuan** [comment]
Are you using Windows? What are the versions of your R and showtext?

It may be the case that your temporary folder is not writable. Can you confirm this? (The temporary directory can be obtained by calling `tempdir()`.)

**Comment by kietoljw** [comment]
Unbelievable!I am so honored to receive your reply!
I am using windows and the versions of R and showtext are latest.
The temporary directory is&nbsp;"C:\\Users\\里高房价\\AppData\\Local\\Temp\\RtmpiSpQhv"&nbsp; .
Thank you very much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yixuan/showtext"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月3日(星期六) 晚上7:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yixuan/showtext] Error loading of showtext (#48)





 
Are you using Windows? What are the versions of your R and showtext?
 
It may be the case that your temporary folder is not writable. Can you confirm this? (The temporary directory can be obtained by calling tempdir().)

**Comment by kietoljw** [comment]
And I can confirm that the temporary folder is writable because it has some folders.
The picture is as follows:
<img width="681" alt="Snipaste_2021-04-03_23-17-51" src="https://user-images.githubusercontent.com/81357761/113482837-02263200-94d3-11eb-8565-29fe74c2115d.png">

**Comment by kietoljw** [comment]
I loaded the showtext in the same way on the computer of my roommate and there is no problem with it.
Next I looked up the temporary folder in his computer and found that my folder have something his folder have not.
<img width="676" alt="Snipaste_2021-04-03_23-27-33" src="https://user-images.githubusercontent.com/81357761/113483101-541b8780-94d4-11eb-8756-1ca290a3f790.png">
<img width="753" alt="Snipaste_2021-04-03_23-27-48" src="https://user-images.githubusercontent.com/81357761/113483104-57af0e80-94d4-11eb-897c-cfec97b55ab9.png">

**Comment by yixuan** [comment]
I guess it is related to the Chinese username of your account. Try to create a new user and test under that one.

**Comment by kietoljw** [comment]
You  are right! There is no problem with it when I modify the path of temporary folder to avoid  Chinese in the path.
Thank you very much again!

**Comment by yixuan** [comment]
Glad to hear that. :smiley:
