### ISSUE TITLE
Adding fonts on a project basis. Possible?

### ISSUE THREAD

**Issue by ramiromagno** [yixuan/showtext#49]
Is it possible to add fonts on a project basis such that it becomes self-contained and reproducible?

If so, are there any guidelines on how to do it in research compendia? Standard paths for fonts and standard approaches for `font_add`ing with project  visibility?

**Comment by yixuan** [comment]
The easy way is to simply pack a font file with the code files, and use `font_add()` to load the font inside the code.

**Comment by ramiromagno** [comment]
okay, thanks!
