### ISSUE TITLE
Fira Sans returns  freetype: error code 139

### ISSUE THREAD

**Issue by ellisp** [yixuan/showtext#5]
Not sure if this is user error or a bug

``` R
library(showtext)
## Loading Google fonts (http://www.google.com/fonts)
font.add.google("Fira Sans", "fira")

## Automatically use showtext to render text for future devices
showtext.auto()

png("test_fira.png", 1000, 1000, res = 200)
   par(family = "fira")   
   plot(1:10, 1:10, main = "Fira Sans test")
dev.off()
```

Returns 50 warnings:

```
50: In title(...) : freetype: error code 139
```

and this image:

![test_fira](https://cloud.githubusercontent.com/assets/5740570/9504569/66d44d76-4c91-11e5-9bab-6e4880ceeed6.png)

**Comment by yixuan** [comment]
Hi @ellisp ,

Thanks for reporting this issue. I believe it is a bug in `showtext`, and I'll try to figure it out.
Just to let you know that the `pdf()` and `CairoPNG()` devices will work, so you can tentatively use those before I fix the bug.

**Comment by ellisp** [comment]
Hi - just checking in with an update that now it crashes at an earlier stage (after a fairly long pause):

``` R
> font.add.google("Fira Sans", "myfont")
Error in font.add(family, r.file, b.file, i.file, bi.file) : 
  freetype: unknown file format, error code 2
```

**Comment by yixuan** [comment]
Sorry @ellisp 
It's still unclear what leads to this error. Have you met any problem with fonts other than Fira Sans?

**Comment by ellisp** [comment]
I haven't, but I haven't looked at many either. I'll rig up a test somehow.

**Comment by yixuan** [comment]
It seems to the problem of the font...

See
https://code.google.com/p/googlefontdirectory/issues/detail?id=368
and
https://github.com/google/fonts/issues/10

**Comment by yixuan** [comment]
The current version of the Fira Sans font should have already solved the problem.
