### ISSUE TITLE
White patches when using Google Fonts Inter in *.pdf

### ISSUE THREAD

**Issue by thomasjwood** [yixuan/showtext#52]
`showtext` is great, use it everyday--thanks for such a useful package!

Is this--the white patch at the joint of the lowercase 't'--a bug in the way that Inter is rendered in a *.pdf?

```
library(tidyverse)
library(showtext)

font_add_google("Inter")
showtext_auto()

p1 <- ggplot() +
  labs(title = "This is an Inter title") +
  theme_minimal(base_family = "Inter")

ggsave("inter_plot.pdf", p1, width = 6, height = 3)
```

![image](https://user-images.githubusercontent.com/1422023/125649783-3a5ca840-2b45-48ba-aeb8-089744372d71.png)

**Comment by yixuan** [comment]
Thansk. I think it has been fixed in the current version on Github. Could you give it a try?

**Comment by thomasjwood** [comment]
Fixed! Thanks!

**Comment by thomasjwood** [comment]
Fixed in current version
