### ISSUE TITLE
How to determine font family name from google fonts?

### ISSUE THREAD

**Issue by rempsyc** [yixuan/showtext#56]
I wonder if it would be helpful in the readme file to add a note about how to determine font family name from google fonts. For instance, one example I have is:

```
## Loading Google fonts (http://www.google.com/fonts)
font_add_google("Inconsolata", "incon")
```

And the example works. But going on the [Inconsolata page](https://fonts.google.com/specimen/Inconsolata?preview.text=test&preview.text_type=custom&query=Inconsolata#standard-styles), I don't see how I could infer that the family name is "incon". As a matter of fact, searching for "incon" with Ctr+F yields no result on that page.

In my case, I am trying to get the [Shizuru font ](https://fonts.google.com/specimen/Shizuru?preview.text=test&preview.text_type=custom) with an Open Font License but cannot find it because I am not sure of the correct font family name to specify (I have also checked their website but could not find this information) :

```
font_add_google("Shizuru", "Shibuya")
Error in search_db(name, db_cache, handle) : font not found
```

I have tried with and without capital with the same outcome. Thanks.

**Comment by yixuan** [comment]
Maybe this is because the "Shizuru" font was newly added by Google, and the font database in `sysfonts` was not up-to-date. You can add the `db_cache = FALSE` parameter to `font_add_google()` so it will fetch the newest information from Google Fonts.

```r
font_add_google("Inconsolata", "incon", db_cache = FALSE)
font_add_google("Shizuru", "Shibuya", db_cache = FALSE)
```

Typically I will update the font database when I submit a new version of the `sysfonts` package, so in a future version you can access the Shizuru font without the additional parameter.

**Comment by rempsyc** [comment]
Thank you for mentioning the `db_cache` argument, I had read about it before but didn't understand it correctly. I can confirm it works!

However, I also found out how to find the correct family font name from the google font page. Once on the page, simply click on "`+ Select this style`", and in a second step, click at the very top-right icon (three squares plus a plus sign and a small orange circle), "`View your selected families`". This will open a side menu with the selected font and at the very bottom you will see something like this:

`font-family: 'Shizuru', cursive;`

Therefore, in addition to the cache, the correct font family name for `Shizuru` was `cursive`, not `Shibuya` (which was the author name actually). So the correct call was:

`font_add_google("Shizuru", "cursive", db_cache = FALSE)`

I hope it will help future readers wondering the same thing! 😊

**Comment by yixuan** [comment]
Just to clarify: the `family` parameter in `font_add_google()` can be **ANY** string, because this is the name you are going to use in R plotting functions. It has nothing to do with the actual family name of the font.

**Comment by rempsyc** [comment]
Ooooh this is actually so useful to know! Documentation from `?font_add_google` simple states:

`family name of the font that will be used in R`

So I interpreted it as having to have the "correct" answer. And the readme really doesn't make it much clearer. I wonder if it would be helpful to add small a note about this somewhere? :D

**Comment by yixuan** [comment]
OK. I'll update the documentation in a future release.
