### ISSUE TITLE
Installing showtext on databricks?

### ISSUE THREAD

**Issue by JegorG** [yixuan/showtext#58]
Sorry if this is not correct support channel but I am trying to install Showtext on databricks, all other packages works fine. 

I try installing freetype using:

%sh
apt-get install libfreetype6-dev

and it looks like its already installed:

Reading package lists...
Building dependency tree...
Reading state information...
libfreetype6-dev is already the newest version (2.10.1-2ubuntu0.1).
0 upgraded, 0 newly installed, 0 to remove and 12 not upgraded.

**Comment by JegorG** [comment]
... But when I try installing it in R I get the following error:

* installing *source* package ‘sysfonts’ ...
** package ‘sysfonts’ successfully unpacked and MD5 sums checked
** using staged installation
checking for gcc... gcc -std=gnu99
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc -std=gnu99 accepts -g... yes
checking for gcc -std=gnu99 option to accept ISO C89... none needed
checking for pkg-config... no
checking for deflate in -lz... yes
checking for png_init_io in -lpng... yes
checking for freetype-config... no

****************************************************
Error: freetype-config not found.
Please install FreeType with freetype-config script.
If you have not installed FreeType, you can
download the source code from http://freetype.org/

**Comment by coroa** [comment]
This affects all linux based systems (at least debian based). Freetype2 dropped support for `freetype-config` in favour of using `pkg-config` directly. https://savannah.nongnu.org/bugs/?53093

**Comment by coroa** [comment]
Sorry for that unhelpful remark. I see that you also support pkg-config for years :). If it is available.

@JegorG You need to install pkg-config.

**Comment by JegorG** [comment]
@coroa THanks, that solved the issue!

**Comment by yixuan** [comment]
Sounds good. So it seems we can close this issue.
