### ISSUE TITLE
Acrobat distortions for certain fonts

### ISSUE THREAD

**Issue by thomasjwood** [yixuan/showtext#59]
Great package, used every time I make a figure in R.

There's a weird bug where Acrobat distorts lower case "l"s. A minimal reproducible example:
```
library(showtext)
library(ggplot2)

font_add_google("Roboto")

p1 <- ggplot(mtcars) +
  geom_blank() +
  labs(
    title = "Lollipop"
  ) +
  theme_minimal(base_family = "Roboto")

showtext_auto()
ggsave("plot 1.pdf")
```

when I open this pdf in Sumatra, it renders fine 

![This is an image](https://i.imgur.com/uConm8K.png)

Open the same file in Acrobat, and the lower case "l"s are weirdly rendered--blocky with inconsistent widths. 

![This is an image](https://i.imgur.com/VhrijiB.png).

Is this a known bug?

**Comment by yixuan** [comment]
It also looks normal in my PDF viewer (PDF-XChange). So I suppose there is some rendering issue in Acrobat? You may also try a different version of Acrobat to see if the problem remains.

![Untitled](https://user-images.githubusercontent.com/216398/169923892-48e34bc6-c391-49ac-b830-d8b3d68569ef.png)
