### ISSUE TITLE
showtext, ggplot2 and shinyapps

### ISSUE THREAD

**Issue by Spatial-R** [yixuan/showtext#6]
Thanks for you showtext package. Recently, i want to use the WenQuanYi Micro Hei to show Chinese characters in my figures. After loading the font using the codes `font.add("wqy", regular = "wqy-microhei.ttc")` , the Chinese characters will show well in the figures created by the basic figure system but not for that created by the ggpplot2 package（ set using the codes: theme_bw(base_family="wqy")） after publishing to the shinyapps. 
How could i solve the problem? Thanks

**Comment by yixuan** [comment]
Hi Bing,
Did you call the `showtext.auto()` or `showtext.begin()` function? Could you show me a piece of code?
And actually `showtext` already contains a copy of the Micro Hei font, via the family name `wqy-microhei`, so you can directly use that one.

**Comment by Spatial-R** [comment]
library(shiny);library(ggplot2);library(showtext)

ui <- shinyUI(fluidPage(
   titlePanel("Old Faithful Geyser Data"),
   sidebarLayout(
      sidebarPanel(
         sliderInput("bins", "Number of bins:", min = 1,  max = 50, value = 30) ),
      mainPanel(plotOutput("distPlot"))
   )))

server <- shinyServer(function(input, output) {  
   output$distPlot <- renderPlot({
     showtext.begin()
      x    <- faithful[, 2] 
      ggplot(data=dat,aes(x=x,y=x))+geom_point()+
        theme_bw(base_size = 12,base_family ="wqy-microhei")
      showtext.end()
   })
})
shinyApp(ui = ui, server = server)

**Comment by yixuan** [comment]
It works on my machine. Did you forget to `print()` the ggplot2 graph?

``` r
library(shiny);library(ggplot2);library(showtext)

ui <- shinyUI(fluidPage(
    titlePanel("Old Faithful Geyser Data"),
    sidebarLayout(
        sidebarPanel(
            sliderInput("bins", "Number of bins:", min = 1, max = 50, value = 30) ),
        mainPanel(plotOutput("distPlot"))
    )))

server <- shinyServer(function(input, output) {

    output$distPlot <- renderPlot({
        showtext.begin()
        g = ggplot(data = faithful, aes(x = eruptions)) +
            geom_histogram(bins = input$bins) +
            ggtitle("直方图") +
            theme_bw(base_size = 30, base_family = "wqy-microhei")
        print(g)
        showtext.end()
    })
})

shinyApp(ui = ui, server = server)
```

![showtext_shiny](https://cloud.githubusercontent.com/assets/216398/13449988/9d9441d0-dffe-11e5-8561-82a150d67376.png)

**Comment by Spatial-R** [comment]
Thanks! I had solved the problem using the way!

**Comment by yixuan** [comment]
Great! Then I'll close this issue.
