### ISSUE TITLE
有没有可以调用Narrow字体的方法？

### ISSUE THREAD

**Issue by Guiquan-27** [yixuan/showtext#61]
非常感谢作者提供的R包，辛苦了！

如题，例如调用Arial Narrow字体？谢谢~

**Comment by yixuan** [comment]
```r
library(showtext)
font_add("arialnarrow", regular = "ARIALN.TTF", bold = "ARIALNB.TTF",
    italic = "ARIALNI.TTF", bolditalic = "ARIALNBI.TTF")
showtext_auto()

plot(1, type = "n")
text(1, 1, "Arial Narrow", family = "arialnarrow", cex = 5)
```

**Comment by Guiquan-27** [comment]
> ```r
> library(showtext)
> font_add("arialnarrow", regular = "ARIALN.TTF", bold = "ARIALNB.TTF",
>     italic = "ARIALNI.TTF", bolditalic = "ARIALNBI.TTF")
> showtext_auto()
> 
> plot(1, type = "n")
> text(1, 1, "Arial Narrow", family = "arialnarrow", cex = 5)
> ```

非常感谢！
