### ISSUE TITLE
Small text when used with the ragg device

### ISSUE THREAD

**Issue by trangdata** [yixuan/showtext#62]
Hi @yixuan thank you for this wonderful package! 🚀 

This is related to #32 but I'm not sure if the issue is completely resolved for me. After [setting RStudio Graphics Device Backend to AGG](https://github.com/r-lib/ragg#use-ragg-in-rstudio), I get the "small text" as [Carson did](https://github.com/yixuan/showtext/issues/32#issuecomment-624350369). I would like the text to be how it's scaled originally, before I call `showtext::showtext_auto()`.

``` r
library(ggplot2)
ggplot(mtcars, aes(wt, mpg)) +
  geom_point(aes(color = factor(cyl))) +
  scale_color_discrete(name = "Some very loooong name")
```
![image](https://user-images.githubusercontent.com/1679452/201675244-3f3bea55-d18f-4412-910a-4a3937b1b105.png)

``` r
showtext::showtext_auto()
ggplot(mtcars, aes(wt, mpg)) +
  geom_point(aes(color = factor(cyl))) +
  scale_color_discrete(name = "Some very loooong name")
```
![image](https://user-images.githubusercontent.com/1679452/201675307-00eb3d2d-844d-48f3-b963-9e9c67ae2575.png)

Any help/comment is much appreciated!

``` r
packageVersion("showtext")
#> [1] '0.9.5'
```

```
RStudio 2022.02.1+461.pro1 "Prairie Trillium" Release (56cbe694f2a30adbc8ffb2aa93cc32bc18dfabdd, 2022-03-22) for macOS Mozilla/5.0 (Macintosh; Intel Mac OS X 12_6_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
```

**Comment by yixuan** [comment]
It seems that somehow RStudio sets a different resolution parameter at the backend. You can try to manually set the `dpi` option after calling `showtext::showtext_auto()`:

```r
showtext::showtext_auto()
showtext::showtext_opts(dpi = 192)
ggplot(mtcars, aes(wt, mpg)) +
  geom_point(aes(color = factor(cyl))) +
  scale_color_discrete(name = "Some very loooong name")
```

**Comment by yixuan** [comment]
By the way, if you are using `ragg`, then it has a built-in font system. See the example at https://ragg.r-lib.org/.

**Comment by trangdata** [comment]
Thank you so much @yixuan for the response. 🌻  `showtext::showtext_opts(dpi = 192)` works for me as a workaround. 🎉 

### Some background
I'm aware of `ragg` built-in font system, but I was hoping to not have to use ragg often. I ran into this problem trying to git-backed deploy/knit an Rmd to html on the RSConnect server. Everything looks fine when I knit locally, but RSConnect server defaults to the ragg_png device and ignores my
``` r
knitr::opts_chunk$set(dev = "png")
```
and, as you mention, has its own resolution as well. I tried adjusting the other options, dpi, fig.retina, etc. but couldn't get it to work right until `showtext::showtext_opts`.
