### ISSUE TITLE
showtext and RStudioGD

### ISSUE THREAD

**Issue by jolars** [yixuan/showtext#7]
`showtext` does not work with RStudio's built-in graphics device, despite working flawlessly with `windows()`. It might for example look like this:

![Imgur](http://i.imgur.com/59RcvmS.jpg)

This is [a known issue](https://journal.r-project.org/archive/2015-1/qiu.pdf), but has not yet been fixed.

**Comment by yixuan** [comment]
I guess it's a bit complicated. RStudio's internal graphics device actually consists of two devices: one used to fast preview and the other for the real rendering of graphics. `showtext` can only affect one of them which results in the failure of using `showtext`.

**Comment by jolars** [comment]
I see, that's too bad. Can you think of any solution or should I close this down?

**Comment by yixuan** [comment]
I would keep it as an open issue, which reminds me of this problem. :smile:

**Comment by benjaminrobinson** [comment]
Any update on this issue?

**Comment by yixuan** [comment]
@benjaminrobinson I apologize for my non-response. I haven't found a way to solve this issue yet, so you still need to manually open new graphics devices to make `showtext` work.

**Comment by yixuan** [comment]
Hi All,

I just figured out a workaround for this issue. The solution is actually simple: before you create plots, run the following code in the RStudio session:

```r
trace(grDevices::png, exit = quote({
    showtext::showtext_begin()
}), print = FALSE)
```

Note that this will enable `showtext` for the RStudio graphics device even if you haven't called `showtext_auto()`. To turn off, use

```r
untrace(grDevices::png)
```

Please let me know if this works for you.

**Comment by yixuan** [comment]
The new version (0.9) has already [solved this issue](https://cran.r-project.org/web/packages/showtext/news.html).
