### ISSUE TITLE
Feature request: Stand-alone raster generation

### ISSUE THREAD

**Issue by coolbutuseless** [yixuan/showtext#70]
I would like to generate stand-alone images with text - without going through the graphics device.

e.g.  something like: `im <- showtext::create_raster("Hello", font = ...., size = ..., color = ..., ...)`

Where the returned `im` is a nativeRaster holding just the rendered text and snugly cropped to the extents of the text.

Is this a feature within the scope of this package?  Or should I fork?

**Comment by yixuan** [comment]
Hi @coolbutuseless, there is indeed an early package exactly designed to do this: https://github.com/yixuan/fontr. The code is really old, so I am not sure if it still works out of the box. But I believe the core part should be OK, possibly with some minor modifications. If you are interested in, feel free to edit and make a fork or pull request.

**Comment by coolbutuseless** [comment]
`fontr` seems limited to single glyphs but `showtext` handles multiple glyphs + kerning.  Is my understanding correct?

I think my current plan will be to fork `showtext` and get something going.  Not sure if it will be worthy of a PR - as my needs are a bit orthogonal to graphics device output.

**Comment by yixuan** [comment]
I see. Yeah, `fontr` only handles a single character. For your purpose, I think you just need to look at https://github.com/yixuan/showtext/blob/master/src/raster.c, and extract some relevant code from there.
